### ISSUE TITLE
Homework due on Fri 11/02

### ISSUE THREAD

**Issue by ghbondar** [ghbondar/webDevClass-Hub#12]
HW-03: Continue to develop and improve your existing HTML and CSS: 
1) Add styling to different selectors besides the background (body-element):
- change the background color of only a section of your document.
- change the font-family for only part of your document.
- For other ideas, see: [w3 Schools CSS Reference](http://www.w3schools.com/css/) and check out colors at: [Paletton](http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF), see our [Intro to CSS](http://dh.newtfire.org/explainCSS.html), and see our [Github Issue about fonts](https://github.com/ghbondar/webDevClass-Hub/issues/10), and the [HTML and CSS tutorial](https://learn.shayhowe.com/html-css/building-your-first-web-page/).
2) Remove all in-line CSS (CSS-styling that is part of the HTML file) that might be present, if you have recycled code from earlier in the course.  
3) As you are probably adding to your existing HTML and CSS files, you are required to use comments in both HTML and CSS to identify these changes:  
`<!-- ghb 2018-10-31: This is a comment in an HTML file -->`  
`/* ghb 2018-10-31: This is a comment in a CSS file*/`  
When you make a change or add something, briefly describe the change to your code, with your initials and the date.
4) After uploading to webpage, check to see if your HTML and CSS are valid using the validator sites:
Validate your HTML: https://validator.w3.org/
Validate your CSS: http://jigsaw.w3.org/css-validator/
5) Remember to push your code to your **personal** Github repo when you are done.

**Comment by Jazour11** [comment]
http://newtfire.org/~jaz66/
