### ISSUE TITLE
Homework 5 due Wed Nov 6

### ISSUE THREAD

**Issue by ghbondar** [ghbondar/webDevClass-Hub#14]
Homework-05:
1) Create a NEW HTML-file called resume.html that lists your skills and experiences. Of course, most of you are just starting out developing careers, so you might not think that you have much to write about, but here is a guide to give you some ideas: https://www.jobscan.co/resume-writing-guide. (do not actually submit any info to that site, however.) Certainly, all of you are high school grads, attending the University of Pittsburgh at Greensburg, and you are taking, and will take, or have taken, other courses. **DO NOT INCLUDE SUPER-PERSONAL INFORMATION, such as your Social Security number**, probably not your real phone number, or street address... just use UPG's campus address: 150 Finoli Dr, Greensburg, PA 15601 if you want to include a fake phone number for formatting purposes, you can use (724) 555-0150 (which is reserved for entertainment purposes). However, it is not recommended that you include fake skills or experiences on your resume.
2) Write the HTML of your resume so that it includes structure through: `<header>, <article>, <section>, <aside>, <footer>` as seen here: Semantic HTML tutorial and link it to your Homepage (index.html). Also, consider using various H-elements (h1, h2, etc.) and class-attributes.
3) Add a link to your resume.html file on your Homepage (index.html).
4) Your resume.html should be linked to, and styled by, a standard central .css file. As usual, make sure that there is no internal or in-line CSS in your HTML files.
5) Remember that you are required to use comments in both HTML and CSS:
`<!-- ghb 2018-10-31: This is a comment in an HTML file -->`
`/* ghb 2018-10-31: This is a comment in a CSS file*/`
When you make a change or add something, briefly describe the change to your code, with your initials and the date, as above.
6) After uploading to webpage, check to see if your HTML and CSS are valid using the validator sites:
Validate your HTML: https://validator.w3.org/
Validate your CSS: http://jigsaw.w3.org/css-validator/
7) As usual, push all content to your personal Github repos and to your webspace.
8) DO NOT USE A RESUME TEMPLATE that does the formatting for you: the HTML and CSS will be incorrect.

**Comment by ghbondar** [comment]
Remember to add a link to your resume.html file on your Homepage (index.html). View the rest of the assignment here in Github! https://github.com/ghbondar/webDevClass-Hub/issues/14

**Comment by KhuongNgx** [comment]
http://newtfire.org/~khn5/

**Comment by chrisc6** [comment]
http://newtfire.org/~cbc40/

**Comment by Jazour11** [comment]
http://newtfire.org/~jaz66/
