### ISSUE TITLE
Homework 7: Boxes and Flexboxes (due Mon Nov 12)

### ISSUE THREAD

**Issue by ghbondar** [ghbondar/webDevClass-Hub#17]
**Homework 7:** Continue to improve one or both of your web pages:
1) Use the CSS Box Model, which we went over in class on Friday, as seen in the [tutorial](https://internetingishard.com/html-and-css/css-box-model/#changing-box-behavior), to improve the layout of one of your HTML documents by adjusting the padding, border, and margins of your text blocks.
2) Then, SOMETHING NEW! Use Flexboxes to arrange the horizontal and vertical placement of your text-blocks and/or images instead of using awkward sets of spaces to position your content horizontally: Please learn how to do this in the [Flexbox tutorial](https://internetingishard.com/html-and-css/flexbox/).

3) **As usual:**
a) make sure that there is no internal or in-line CSS in your HTML files.
b) use comments in both HTML and CSS, with initials and date, to indicate your modifications:
`<!-- ghb 2018-10-31: This is a comment in an HTML file -->`
`/* ghb 2018-10-31: This is a comment in a CSS file*/`
c) after uploading to web space, check to see if your HTML and CSS are valid using the validator sites:
Validate your HTML: https://validator.w3.org/
Validate your CSS: http://jigsaw.w3.org/css-validator/
d) push all content to your personal Github repos and to your webspace.

**Comment by Jazour11** [comment]
http://newtfire.org/~jaz66/

**Comment by KhuongNgx** [comment]
http://newtfire.org/~khn5/
