### ISSUE TITLE
Using lines as rectangles

### ISSUE THREAD

**Issue by Jazour11** [ghbondar/webDevClass-Hub#19]
On the most recent homework for the svg graph, I am wondering if we are allowed to use the <line  with the expanded width like we did in class as the the graphs rectangles.

Thank you,
Jake Zourelias

**Comment by ghbondar** [comment]
Yes, indeed! ...it looks the same and it's probably simpler. The main difference is that you don't get an outline, but that's just a matter of style. @Jazour11
