### ISSUE TITLE
Homework 9: Processing Images (due Fri 11/16)

### ISSUE THREAD

**Issue by ghbondar** [ghbondar/webDevClass-Hub#21]
**Homework 9: Processing Images**
1) Take two or three tasteful pictures with your phone or camera and upload them to your computer, or a campus computer. Email is one way you can do this.
2) Using Adobe Photoshop (on a campus machine, unless you have a copy) resize them to 1024x768 px.:
`Go to Image-menu, then down to Image Size.`
Or you can use other image processing software that you have access to.
3) Display these pictures, and your SVG-image, inside [Flexboxes](https://internetingishard.com/html-and-css/flexbox/) on your Homepage (index.html) or a new page that is linked to your Homepage.
More [Fun with Flexboxes in our Github Issue](https://github.com/ebeshero/DHClass-Hub/issues/533)!
4) Store your image-files inside a new folder named "img" or "images". When linking to your image-files in your HTML-file, remember to add this directory to the link:
`<img src="img/filename.jpg" alt="description here"/>`

5) **As usual:**
a) make sure that there is no internal or in-line CSS (or **image-sizing**) in your HTML files .
b) use comments in both HTML and CSS, with initials and date, to indicate your modifications:
`<!-- ghb 2018-10-31: This is a comment in an HTML file -->`
`/* ghb 2018-10-31: This is a comment in a CSS file*/`
c) after uploading to web space, check to see if your HTML and CSS are valid using the validator sites:
**Validate your HTML: https://validator.w3.org/
Validate your CSS: http://jigsaw.w3.org/css-validator/**
d) push all content to your personal Github repos and to your webspace.

**Comment by Jazour11** [comment]
http://newtfire.org/~jaz66/
