### ISSUE TITLE
Trouble linking SSi

### ISSUE THREAD

**Issue by Jazour11** [ghbondar/webDevClass-Hub#28]
Hello,

I am having trouble linking my ssi. On my old web page main would take you back to the main page from all of the linked web pages. I currently have it in its own folder, and have it as a link in all of my pages. It buttons for main shows up, but it only works on the index.html. I tried to go through the code, and I can not find what is wrong here. Any help would be greatly appreciated.
New Page http://newtfire.org/~jaz66/
Old Page http://newtfire.org/~jaz66/old/

Best regards, 
Jake Zourelias

**Comment by ebeshero** [comment]
@Jazour11 Did you check the “x-bit” permissions for these files on the newtfire server? The pages need to executable (x) as well as readable (r) by visitors for the SSI to work. See if the file permission settings in the server look the same for index.html as for your other files.

**Comment by Jazour11** [comment]
Hello,
Thank you for the quick reply. I went ahead and checked that, and executables were not checked on the index.html file, but they were on the other files, so I made sure the were all checked including the index.html , but it was still not working. When I click the main on the main index.html file it reloads the page, but when I click it on any of the other webpages it says Not Found The requested URL /~jaz66/resume/index.html was not found on this server.

**Comment by ebeshero** [comment]
@Jazour11 Aha—I bet I know what it is: Check your file directories and where your SSI file is sitting in relation to them. I bet your SSI and index.html are in the same directory level, but these others are in inner directories, right? 

If that is the case, you just need to change the way you reference the SSI from that SSI line that looks like a comment in your inner-directory HTML files. You need to set it to climb up out of the inner directory and reach for the SSI file in the main directory. If your files are nested in just one directory down from the main, you want to reach it like this: `../yourSSI.html`

**Comment by Jazour11** [comment]
Unfortunately that does not work either. At first I had it without the .. and it did not show up at all what I added the .. to drop a directory it now shows the ssi, but it does not work

**Comment by ebeshero** [comment]
@Jazour11 I am taking a look at your directories in Newtfire. I am pretty sure this is a file referencing issue.

**Comment by ebeshero** [comment]
@Jazour11 It *is* working! Look at your car page: http://newtfire.org/~jaz66/html/car.html 
Your SSI is simply the little menu bar that goes to Main and About. It's properly loading on that page and on your others when I click around on the published site on the web, so it looks like you corrected the problem? Or is something else wrong?

**Comment by Jazour11** [comment]
Yea I think it is working now. It was weird because it was not working right after I uploaded the files but it seems to be good now. Thank you very much for all the help tonight on this. Have a good rest of your night.

Best regards,
Jake Zourelias

**Comment by ebeshero** [comment]
I’m glad it is working now!

**Comment by Jazour11** [comment]
For some reason it seems to not be working again. I am wondering if this is an issue with my browser or computer. I was wondering if anyone can see if main take them back to the main page from another one of my linked web pages  http://newtfire.org/~jaz66/html/car.html. I apologize for all of the issue. 

Best regards,
Jake Zourelias

**Comment by ebeshero** [comment]
@Jazour11 Sorry! I didn't understand the problem earlier. Your SSI is loading, but its links are NOT pointing correctly, as you noticed. This is probably because the index.html page is not in the same file directory as the inner pages. Probably you should make a new SSI to handle links from inside this directory up to the main level. Save this SSI in the same inner directory as car.html.

**Comment by ebeshero** [comment]
@Jazour11 I'm sorry the linking with subdirectories is complicated--I'm about to be driving a lot and can't help you with the details, but you're going to have to figure out the climbing up from one directory to another, using `../index.html`, and the way to position the new SSI on your own with some trial and error. You can do it.

**Comment by Jazour11** [comment]
Okay i think I can figure it out from there. Safe Travels,

Best Regards,
Jake Zourelias
