### ISSUE TITLE
github to newtfire?

### ISSUE THREAD

**Issue by hmh49** [ghbondar/webDevClass-Hub#4]
Hello, right now I have my webpage created here: file:///C:/Users/hhost/Documents/Github/hannahHrepo/index.html

I thought I followed all the necessary steps but my link, http://newtfire.org/~hmh49/, hasn't changed to my updated webpage. How can I do this?

Thanks

**Comment by ebeshero** [comment]
Hi, @hmh49! Did you try sending your files to your web space? (Are you using FileZilla for that?) I am about to board a plane so I can’t get out my computer and check the newtFire server right now...but let us know what you tried.

**Comment by hmh49** [comment]
yes i have everything in the public html file in filezilla.

**Comment by quantum-satire** [comment]
Hi @hmh49 
Did you rename your file to index.html? Your main page will only display if it's named that!

**Comment by hmh49** [comment]
that was my issue! thank you

**Comment by ebeshero** [comment]
Yay! I just saw your page go live here on my plane. :-) congrats, @hmh49 and thank you @quantum-satire !

**Comment by hmh49** [comment]
thank you both for the help!!
