### ISSUE TITLE
Error message after git push:

### ISSUE THREAD

**Issue by Ivurik** [ghbondar/webDevClass-Hub#8]
remote: Permission to ghbondar/webDevClass-Hub.git denied to Ivurik.
fatal: unable to access 'https://github.com/ghbondar/webDevClass-Hub.git/': The requested URL returned error: 403

**Comment by ghbondar** [comment]
@Ivurik Github is still telling me that you need to accept the invite. Here it is:  
[https://github.com/ghbondar/webDevClass-Hub/invitations](https://github.com/ghbondar/webDevClass-Hub/invitations  )

**Comment by ghbondar** [comment]
@Ivurik Also! You should be pushing files to YOUR PERSONAL Github repo:
https://github.com/Ivurik/Ivurik
NOT to ghbondar/webDevClass-Hub.
